language: python
python:
    - "2.7"
before_install:
    - "sudo apt-get update"
    - "sudo apt-get install libgeoip1 -y"
install:
    - "pip install coveralls tox"
script:
    - "tox"
after_success:
    - "coveralls"
